version: '3.4'

services:
  awsLocalStack:
    image: localstack/localstack:latest
    ports:
      - 4510-4559:4510-4559
      - 4566:4566
    environment:
      - SERVICES=sqs,sns,dynamodb,secretsmanager
      - DEBUG=1
  
  awsCli:
    image: amazon/aws-cli:latest
    stdin_open: true
    tty: true
    entrypoint: ./startupServices.sh
    depends_on:
    - awsLocalStack
    environment:
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_DEFAULT_OUTPUT=json
    volumes:
      - ./:/aws    